### ISSUE TITLE
NPM warning: incorrect UMD name

### ISSUE THREAD

**Issue by nuintun** [ampproject/remapping#173]
![企业微信截图_20220427142726](https://user-images.githubusercontent.com/1730277/165455286-0f686be3-36f7-4245-938f-cd8380751a8b.png)

**Comment by jridgewell** [comment]
Hi @nuintun: I [deprecated](https://www.npmjs.com/package/@jridgewell/set-array/v/1.0.0) `@jridgewell/set-array@1.0.0` due to it having an incorrect UMD name when generating the build. I released [v1.0.1](https://www.npmjs.com/package/@jridgewell/set-array/v/1.0.1) (and now v1.1.0) which is fixed and the [dependency range in `@jridgewell/gen-mapping`](https://github.com/jridgewell/gen-mapping/blob/aafac50fa2eb44fb5a3b18758ee8c27e78b41127/package.json#L69) should allow the new releases to be used.

**Comment by Guria** [comment]
@jridgewell it seems there is no new version of `@jridgewell/gen-mapping` with proper range in dependencies were released.
https://unpkg.com/@jridgewell/gen-mapping@0.1.0/package.json which is 0.1.0 as of for now and still has strict 1.0.0 as dependency

**Comment by jridgewell** [comment]
Ahhh, thank you for pointing that out! I'll release a new version of gen-mapping in a few minutes.

**Comment by jridgewell** [comment]
`@jridgewell/gen-mapping@v0.1.1` is now released, which allows any v1 `jridgewell/set-array` version.
